# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Tented.Tented
PackageVersion: 0.2.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Protocols:
- tented
ProductCode: Tented
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/tented-app/tented-releases/releases/download/v0.2.0/Tented_0.2.0_x64-setup.exe
  InstallerSha256: D09512A194C8D637C4666C29CE547CA0730CB92DBE75A2DD64B77EB0340894AA
ManifestType: installer
ManifestVersion: 1.12.0
